# Generated by Django 5.1.3 on 2024-12-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(max_length=40),
        ),
    ]
