# Generated by Django 5.1.3 on 2024-11-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cast_image', models.ImageField(blank=True, upload_to='photos/categories')),
            ],
        ),
    ]
